export const rawMockUsers = [
  {
    id: 1,
    nickname: '주현주현',
    role: '개발자',
    career: '주니어',
    introduction: '프론트엔드 개발에 진심인 주현입니다!',
    topic1: 'AI/머신러닝',
    topic2: '프론트엔드',
    topic3: 'API 설계',
    imageUrl: 'https://via.placeholder.com/150',
  },
  {
    id: 2,
    nickname: '코딩짱',
    role: '개발자',
    career: '미들',
    introduction: '데이터와 서버를 책임지는 백엔더!',
    topic1: 'Spring Boot',
    topic2: 'Redis',
    topic3: 'OAuth2',
    imageUrl: 'https://via.placeholder.com/150',
  },
  {
    id: 3,
    nickname: 'UI디자이너',
    role: '디자이너',
    career: '시니어',
    introduction: '감성 UI/UX 제작자',
    topic1: 'UX 리서치',
    topic2: '프로토타이핑',
    topic3: '인터랙션 디자인',
    imageUrl: 'https://via.placeholder.com/150',
  },
  {
    id: 4,
    nickname: '안주현주현',
    role: '프로젝트 매니저',
    career: '주니어',
    introduction: '프론트엔드 개발에 진심인 주현입니다!',
    topic1: 'AI/머신러닝',
    topic2: '프론트엔드',
    topic3: 'API 설계',
    imageUrl: 'https://via.placeholder.com/150',
  },
  {
    id: 5,
    nickname: '주주현주현',
    role: '학생',
    career: '주니어',
    introduction: '프론트엔드 개발에 진심인 주현입니다!',
    topic1: 'AI/머신러닝',
    topic2: '프론트엔드',
    topic3: 'API 설계',
    imageUrl: 'https://via.placeholder.com/150',
  },
];

export const mockUsers = rawMockUsers.map((user) => ({
  id: user.id,
  nickName: user.nickname,
  role: user.role,
  career: user.career,
  introduction: user.introduction,
  image: user.imageUrl,
  tags: [
    { text: user.topic1, color: '#3B82F6' },
    { text: user.topic2, color: '#10B981' },
    { text: user.topic3, color: '#F59E0B' },
  ],
}));
