name: Close Jira Issue on GitHub Issue Close
on:
  issues:
    types:
      - closed

jobs:
  close-jira-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Jira
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}

      - name: Extract Jira Story Key from GitHub Issue Body
        id: extract-key
        run: |
          ISSUE_BODY="${{ github.event.issue.body }}"
          JIRA_KEY=$(echo "$ISSUE_BODY" | grep -oE '[A-Z]+-[0-9]+')
          echo "JIRA_KEY=$JIRA_KEY" >> $GITHUB_ENV


      - name: Debug Jira Issue Key
        run: |
          echo "Extracted Jira Issue Key: $JIRA_KEY"

      - name: Extract Transition ID for "Done"
        id: extract-transition
        run: |
          TRANSITION_ID=$(curl -s -u "${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}" \
          -X GET -H "Content-Type: application/json" \
          --data '{"transition": {"id": "3"}}' \
          "${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue/${{ env.JIRA_KEY }}/transitions" | \
          jq -r '.transitions[] | select(.name=="작업 완료") | .id')

          echo "Found Transition ID: $TRANSITION_ID"
          echo "TRANSITION_ID=$TRANSITION_ID" >> $GITHUB_ENV

      - name: Move Jira Story to "Done"
        run: |
          RESPONSE=$(curl -s -w "\nHTTP_STATUS=%{http_code}" -u "${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}" \
          -X POST -H "Content-Type: application/json" \
          --data '{"transition": {"id": "3"}}' \
          "${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue/${{ env.JIRA_KEY }}/transitions")

          HTTP_STATUS=$(echo "$RESPONSE" | grep HTTP_STATUS | cut -d= -f2)
          echo "Jira API Response: $RESPONSE"

          if [[ "$HTTP_STATUS" -ne 204 ]]; then
            echo "ERROR: Failed to transition Jira Story to Done. HTTP Status: $HTTP_STATUS"
            exit 1
          else
            echo "SUCCESS: Jira Story transitioned to Done!"
          fi
